### ISSUE TITLE
Can you port this in Dart?

### ISSUE THREAD

**Issue by Emasoft** [gritzko/todomvc-swarm#23]
I'm a Dart developer. I switched to Dart because i found it to be a faster and better javascript. Unfortunately Dart has only two libraries to choose from at this time: AngularDart and PolymerDart. I don't like their approach. I like React, and I like even more your Swarm+React approach. I'd love to use it in Dart, but the language is too young to offering anything like that yet.
So I beg you to port this library in Dart. Possibly as a native middleware, because js interop with dart is cumbersome and slow (Dart is jitted, not interpreted like javascript, increasing the performances up to 4x). Here are some Dart libraries with some very basic react-like features that you can use for jump start the development:

Tiles - https://github.com/cleandart/tiles
TagTree - https://github.com/google/dart-tagtree

I hope you will consider this idea.

**Comment by gritzko** [comment]
We have Java and Go in the pipeline and that will keep us busy for 6 months for sure.
Maybe later.
